platform :ios, '10.0'

target 'scswift-example' do

  use_frameworks!

  pod 'SCSwift', :path => '../'

  target 'scswift-exampleTests' do
    inherit! :search_paths
  end

  target 'scswift-exampleUITests' do
    inherit! :search_paths
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
